apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - express-deployment.yaml
  - express-service.yaml
  - express-ingress.yaml
  - application.yaml

commonLabels:
  app: express
